### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by xenedium** [DaddaAdam/Spring-Reddit#5]
A basic README file to explain the workflows

**Comment by vishalsingh2972** [comment]
@xenedium could you assign this to me?

**Comment by xenedium** [comment]
@vishalsingh2972 Sure !

**Comment by vishalsingh2972** [comment]
Hey @xenedium could you check my PR https://github.com/DaddaAdam/Spring-Reddit/pull/11

**Comment by vishalsingh2972** [comment]
@xenedium have made the changes you requested, please check and merge the PR https://github.com/DaddaAdam/Spring-Reddit/pull/12
@DaddaAdam
